version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:14.7
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # migrate-db:
  #   image: migrate/migrate
  #   volumes:
  #     - ./database/migration:/migrations
  #     - ./database/seeder:/sedeers
  #   command: -path=/migrations/ -database postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable up 1
  #   links:
  #     - postgres
  #   depends_on:
  #     - postgres

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq

volumes:
  redis_data:
  postgres_data:
  minio_data: