apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      automountServiceAccountToken: false
      containers:
        - name: jaeger
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          image: jaegertracing/all-in-one:1.57
          ports:
            - containerPort: 16686

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  selector:
    app: jaeger
  ports:
    - protocol: TCP
      port: 16686
      targetPort: 16686