apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetrycollector

  template:
    metadata:
      labels:
        app.kubernetes.io/name: opentelemetrycollector
    spec:
      automountServiceAccountToken: false
      containers:
        - name: otelcol
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          image: otel/opentelemetry-collector-contrib:0.100.0
          args:
            - --config=/etc/config.yaml
          ports:
            - containerPort: 4317
          volumeMounts:
            - mountPath: /etc/
              name: otelcol-config
      volumes:
        - configMap:
            items:
              - key: config.yaml
                path: config.yaml
            name: otel-collector-config
          name: otelcol-config

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
spec:
  selector:
    app.kubernetes.io/name: opentelemetrycollector
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
  type: ClusterIP
