name: Deployment to Kubernetes

on:
  workflow_call:
    inputs:
      deployment: # The name of the deployment job
        required: true
        type: string
        description: 'The name of the deployment job'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f manifests/
